name: Build macOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.0'
        host: 'mac'
        target: 'desktop'
        modules: 'qtserialport'
        cache: true
        
    - name: Configure CMake
      run: |
        cmake -B build -S nwss-cnc -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release --target nwss-cnc
 
    - name: Create DMG
      run: |
        # Install create-dmg if not available
        if ! command -v create-dmg &> /dev/null; then
          brew install create-dmg
        fi
        
        # Create DMG
        create-dmg \
          --volname "NWSS-CNC" \
          --volicon "nwss-cnc/resources/icons/nwss-cnc-icon.icns" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "NWSS-CNC.app" 150 200 \
          --hide-extension "NWSS-CNC.app" \
          --app-drop-link 450 200 \
          "NWSS-CNC-${{ github.ref_name || 'latest' }}.dmg" \
          "build/NWSS-CNC.app"
          
    - name: Package with CPack (fallback)
      if: failure()
      run: |
        cmake --build build --config Release --target package_for_github
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nwss-cnc-macos
        path: |
          *.dmg
          build/*.dmg
          build/NWSS-CNC.app
        retention-days: 30
        
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.dmg
          build/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 