name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  build-windows:
    name: Build Windows (x64)
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: 'x64'
      
      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Package application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --target package_for_github
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-package-x64
          path: |
            ./nwss-cnc/build/*.zip
            ./nwss-cnc/build/*.exe
  
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            display_name: Intel
            artifact_suffix: intel
          - arch: arm64
            display_name: Apple Silicon
            artifact_suffix: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          # Remove -march=native from compile flags
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_PREFIX_PATH="$Qt6_DIR" \
                 -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
                 -DCMAKE_CXX_FLAGS="-O3"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Package application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --target package_for_github
      
      - name: Rename artifacts for clarity
        working-directory: ./nwss-cnc/build
        run: |
          for file in *.dmg; do
            if [ -f "$file" ]; then
              mv "$file" "${file%.dmg}-${{ matrix.artifact_suffix }}.dmg"
            fi
          done
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-${{ matrix.artifact_suffix }}
          path: ./nwss-cnc/build/*.dmg
  
  build-linux:
    name: Build Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev \
            libx11-dev libxext-dev libxfixes-dev libxi-dev \
            libxrender-dev libxcb1-dev
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_PREFIX_PATH="$Qt6_DIR" \
                 -DCMAKE_CXX_FLAGS="-O3"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Package application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --target package_for_github
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: |
            ./nwss-cnc/build/*.deb
            ./nwss-cnc/build/*.rpm
            ./nwss-cnc/build/*.tar.gz
  
  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is the critical permission needed to create releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Display structure of downloaded files
        run: ls -R artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          name: NWSS CNC ${{ github.ref_name }}
          body: |
            # NWSS CNC ${{ github.ref_name }} Release
            
            SVG to G-Code Converter for CNC machines
            
            ## Downloads
            
            ### Windows
            - Windows 64-bit Installer (.exe)
            - Windows 64-bit Portable (.zip)
            
            ### macOS
            - macOS Intel (intel.dmg)
            - macOS Apple Silicon (arm64.dmg)
            
            ### Linux
            - Ubuntu/Debian package (.deb)
            - Red Hat/Fedora package (.rpm)
            - Portable Linux package (.tar.gz)
            
            ## Changes in this release
            
            [Release notes here]