name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  build-windows:
    name: Build Windows (x64)
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: 'x64'
      
      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Deploy Qt dependencies
        working-directory: ./nwss-cnc/build/Release
        run: |
          # Create a deployment directory
          mkdir -p deploy
          
          # Copy your executable
          Copy-Item "NWSS-CNC.exe" -Destination "deploy/"
          
          # Use windeployqt to copy only required Qt DLLs
          & "$env:Qt6_DIR\bin\windeployqt.exe" --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle --release --verbose 1 "deploy/NWSS-CNC.exe"
          
          # Create a ZIP package
          Compress-Archive -Path "deploy/*" -DestinationPath "NWSS-CNC-win64.zip"
      
      - name: Package with NSIS (optional)
        working-directory: ./nwss-cnc/build
        run: |
          # Run the NSIS packaging - this should be configured to use the "deploy" folder content
          cmake --build . --target package_for_github
          
          # Rename installer for clarity
          Get-ChildItem -Path "." -Filter "*.exe" | Rename-Item -NewName {$_.BaseName + "-win64" + $_.Extension}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-package-x64
          path: |
            ./nwss-cnc/build/*.zip
            ./nwss-cnc/build/*.exe
  
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            display_name: Intel
            artifact_suffix: intel
          - arch: arm64
            display_name: Apple Silicon
            artifact_suffix: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          # Configure with correct architecture
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_PREFIX_PATH="$Qt6_DIR" \
                  -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
                  -DCMAKE_CXX_FLAGS="-O3"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Deploy and Sign app
        working-directory: ./nwss-cnc/build
        run: |
          # Deploy with Qt dependencies
          "$Qt6_DIR/bin/macdeployqt" "NWSS-CNC.app" -always-overwrite -verbose=2
          
          # Sign with ad-hoc certificate for testing
          codesign --force --options runtime --deep --sign - --entitlements ../resources/macos/entitlements.plist "NWSS-CNC.app"
          
          # Create DMG 
          "$Qt6_DIR/bin/macdeployqt" "NWSS-CNC.app" -dmg -verbose=2
          
          # Rename DMG to include architecture
          mv "NWSS-CNC.dmg" "NWSS-CNC-${{ matrix.artifact_suffix }}.dmg"
      
      - name: Create user instructions
        working-directory: ./nwss-cnc/build
        run: |
          # Create a README with instructions for bypassing Gatekeeper
          cat > NWSS-CNC-README.txt << EOF
          NWSS-CNC for macOS ${{ matrix.display_name }}
          --------------------------------------------
          
          If you receive a message that the app is damaged and can't be opened:
          
          Option 1: Right-click (or Control+click) on the app and select "Open" from the menu
          
          Option 2: Run this command in Terminal:
          xattr -rd com.apple.quarantine /Applications/NWSS-CNC.app
          
          These steps are needed because the app is not signed with an Apple Developer certificate.
          EOF
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-${{ matrix.artifact_suffix }}
          path: |
            ./nwss-cnc/build/*.dmg
            ./nwss-cnc/build/NWSS-CNC-README.txt

  build-linux:
    name: Build Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev \
            libx11-dev libxext-dev libxfixes-dev libxi-dev \
            libxrender-dev libxcb1-dev
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtserialport'
          set-env: 'true'
          aqtversion: '==3.2.*'

      - name: Create build directory
        run: mkdir -p nwss-cnc/build

      - name: Configure CMake
        working-directory: ./nwss-cnc/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_PREFIX_PATH="$Qt6_DIR" \
                 -DCMAKE_CXX_FLAGS="-O3"

      - name: Build application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --config Release

      - name: Package application
        working-directory: ./nwss-cnc/build
        run: cmake --build . --target package_for_github
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: |
            ./nwss-cnc/build/*.deb
            ./nwss-cnc/build/*.rpm
            ./nwss-cnc/build/*.tar.gz
  
  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is the critical permission needed to create releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Display structure of downloaded files
        run: ls -R artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          name: NWSS CNC ${{ github.ref_name }}
          body: |
            # NWSS CNC ${{ github.ref_name }} Release
            
            SVG to G-Code Converter for CNC machines
            
            ## Downloads
            
            ### Windows
            - Windows 64-bit Installer (.exe)
            - Windows 64-bit Portable (.zip)
            
            ### macOS
            - macOS Intel (intel.dmg)
            - macOS Apple Silicon (arm64.dmg)
            
            ### Linux
            - Ubuntu/Debian package (.deb)
            - Red Hat/Fedora package (.rpm)
            - Portable Linux package (.tar.gz)
            
            ## Changes in this release
            
            [Release notes here]